apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:c3a3JsT4Um68SogsiRzpErRObMT+SYiL7XkHt7Hs8eGRkm6mG6H3Pw==,iv:exGiD+8eLhUJx3URmusJtgwMxxkEWu+U0L71VLBuzTw=,tag:9wBYW4ySzxSspzy84Tqw4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1edhwupl3894j6fndflfgtth69xet0zhna53nczm52tyrlku52gsswdrhyp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dTVTcTF1UkNXQjhkN0xr
            SnJBVXhPRjRncGZWQU9lTTZCS05vdjZaR0dFCmZNdTdzRGhPaFpUUzY4MDdBSU53
            YU9mekVPTys1RzFoZC94STZmQ1lQbEEKLS0tIDIxTFJ6NUFNVHR3SlpyTXRmS1Vl
            SnFUNHlaRXN0Yk1iUmc2bm00NldxODAKfPQ6YgEqyqiXe5HKGimvx4dLXJBM3Mvp
            QWda4C7quCOAIqpO63wRnbfpmtN65+b7sdcOrgVwRqHnJDX5rc2WpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-13T19:52:49Z"
    mac: ENC[AES256_GCM,data:GR8q6BRzpXtz7jP81SYaM0JvLXbh0N4sjtHqDxuAzPf2bXfOEWoQbNT7AveW/vB8tN045WKA9XTott1txgcHpeep4iPwr3/b9jJyUPFopSyHHMXzXJEouaXwc6qRdrEsYENFFV45p6y/wT2skuJ7mhSnaiSffqngYXyDtAyi5t0=,iv:3YUdhLfhq9ipk2ffJaoyCbtUcmCO3wV/uenIMVQjgFM=,tag:p2WAgX6aBTZY//koZ5uTsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
